import { Navbar } from "@/components";
import AuthProvider from "@/context/AuthProvider";
import ContextProvider from "@/context/ContextProvider";
import QueryProvider from "@/context/QueryProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next JS MovieDB",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>
            <ContextProvider>
              <Navbar />
              {children}
            </ContextProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
